### ISSUE TITLE
Tanya

### ISSUE THREAD

**Issue by bagussatoto** [rahmatagungj/ultra-lightweight-github-rest-client#1]
> # Tanya (#1) <br>
> ## Kalau boleh tahu project ini dibuat seperti apa ya?

**Comment by rahmatagungj** [comment]
Projek ini untuk fetch data dari Github, supaya lebih mudah saja dan tidak perlu menggunakan pustaka tambahan. jadi lebih sederhana dan cepat. @bagussatoto 

Thank you sudah mampir 😄

**Comment by bagussatoto** [comment]
> # Di tunggu project sampai selesai 👏🏽👏🏽

> ## @rahmatagungj
